<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class School extends Model
{
    protected $fillable = [
        'record_type',
        'inep_code',
        'name',

        // 2. Operating Location
        'is_school_building',
        'has_rooms_in_other_school',
        'has_shack_or_similar',
        'is_socio_educational_unit',
        'is_prison_unit',
        'is_other_location',

        // 3. Occupation and Sharing
        'building_occupation_type',
        'is_shared_building',
        'shared_school_inep_1',
        'shared_school_inep_2',
        'shared_school_inep_3',
        'shared_school_inep_4',
        'shared_school_inep_5',
        'shared_school_inep_6',

        // 4. Water Supply
        'provides_potable_water',
        'water_public_network',
        'water_artesian_well',
        'water_cistern',
        'water_river_source',
        'water_truck',
        'no_water_supply',

        // Energy Source
        'energy_public_network',
        'energy_fossil_generator',
        'energy_renewable_source',
        'no_energy_supply',

        // 5. Sanitation
        'sewer_public_network',
        'sewer_septic_tank',
        'sewer_rudimentary_tank',
        'no_sewer_system',

        // 6. Waste Management
        'waste_collection_service',
        'waste_burning',
        'waste_burying',
        'waste_licensed_destination',
        'waste_other_area_disposal',
        'waste_separation',
        'waste_reuse',
        'waste_recycling',
        'no_waste_treatment',

        // 7. Physical Facilities
        'has_warehouse',
        'has_green_area',
        'has_auditorium',
        'has_bathroom',
        'has_pcd_bathroom',
        'has_childhood_education_bathroom',
        'has_staff_bathroom',
        'has_shower_room',
        'has_library',
        'has_kitchen',
        'has_pantry',
        'has_student_dormitory',
        'has_teacher_dormitory',
        'has_science_lab',
        'has_it_lab',
        'has_vocational_lab',
        'has_playground',
        'has_covered_patio',
        'has_uncovered_patio',
        'has_swimming_pool',
        'has_covered_sports_court',
        'has_uncovered_sports_court',
        'has_cafeteria',
        'has_student_rest_room',
        'has_arts_studio',
        'has_music_room',
        'has_dance_studio',
        'has_multipurpose_room',
        'has_open_dirt_field',
        'has_animal_breeding_area',
        'has_principals_office',
        'has_reading_room',
        'has_teachers_lounge',
        'has_special_education_resource_room',
        'has_secretarys_office',
        'has_vocational_workshop_rooms',
        'has_recording_studio',
        'has_agricultural_production_area',
        'has_none_of_the_facilities',

        // 8. Accessibility
        'acc_handrails_guardrails',
        'acc_elevator',
        'acc_tactile_floors',
        'acc_wide_doors_80cm',
        'acc_ramps',
        'acc_visual_alarm',
        'acc_audio_alarm',
        'acc_tactile_signage',
        'acc_visual_signage',
        'no_accessibility_resources',

        // 9. Classrooms and Equipment
        'qty_classrooms_inside',
        'qty_classrooms_outside',
        'qty_classrooms_air_conditioned',
        'qty_classrooms_pcd_accessible',
        'has_satellite_dish',
        'has_computers',
        'has_photocopier',
        'has_printer',
        'has_multifunctional_printer',
        'has_scanner',
        'has_none_of_the_equipment',
        'qty_dvd_bluray_players',
        'qty_sound_systems',
        'qty_tvs',
        'qty_digital_whiteboards',
        'qty_multimedia_projectors',
        'qty_desktop_computers_for_students',
        'qty_laptop_computers_for_students',
        'qty_tablets_for_students',

        // 10. Internet Access
        'internet_admin_use',
        'internet_learning_use',
        'internet_student_use',
        'internet_community_use',
        'no_internet_access',
        'internet_via_school_devices',
        'internet_via_personal_devices',
        'has_broadband',
        'has_wired_lan',
        'has_wireless_lan',
        'no_local_network',

        // 11. Staff
        'staff_agronomists',
        'staff_secretarial_admin_assistants',
        'staff_general_services_maintenance',
        'staff_librarians_reading_monitors',
        'staff_health_emergency_professionals',
        'staff_shift_coordinators',
        'staff_speech_therapists',
        'staff_nutritionists',
        'staff_psychologists',
        'staff_cooks_kitchen_assistants',
        'staff_pedagogical_supervisors',
        'staff_school_secretary',
        'staff_security_guards',
        'staff_it_multimedia_technicians',
        'staff_vice_principals',
        'staff_community_counselors_social_workers',
        'staff_libras_interpreters',
        'staff_braille_translators_assistants',
        'no_staff_in_listed_functions',

        // 12. School Meals and Pedagogical Materials
        'provides_school_meals',
        'has_multimedia_collection',
        'has_early_childhood_toys',
        'has_scientific_materials_kit',
        'has_sound_amplification_equipment',
        'has_agricultural_production_equipment',
        'has_musical_instruments',
        'has_educational_games',
        'has_artistic_cultural_materials',
        'has_vocational_education_materials',
        'has_sports_recreation_materials',
        'has_deaf_bilingual_education_materials',
        'has_indigenous_education_materials',
        'has_ethnic_racial_relations_materials',
        'has_rural_education_materials',
        'has_quilombola_education_materials',
        'has_special_education_materials',
        'has_none_of_the_pedagogical_materials',

        // 13. Indigenous School and Languages
        'is_indigenous_school',
        'teaching_in_indigenous_language',
        'teaching_in_portuguese',
        'indigenous_language_code_1',
        'indigenous_language_code_2',
        'indigenous_language_code_3',

        // 14. Student Selection and Quotas
        'has_entrance_exam',
        'quota_ppi',
        'quota_income',
        'quota_public_school',
        'quota_pcd',
        'quota_other_groups',
        'no_quotas',

        // 15. Management and Communication
        'has_website_or_social_media',
        'shares_space_with_community',
        'uses_neighborhood_facilities',
        'has_parents_association',
        'has_parents_teachers_association',
        'has_school_council',
        'has_student_union',
        'has_other_collegial_bodies',
        'no_collegial_bodies',

        // 16. PPP and Environmental Education
        'ppp_updated_last_12_months',
        'has_environmental_education',
        'env_as_curriculum_content',
        'env_as_specific_subject',
        'env_as_structural_axis',
        'env_via_events',
        'env_via_transdisciplinary_projects',
        'env_none_of_the_options',
    ];
}
